name: ESLint
on: push
jobs:
  ESLint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: ci
        run: cd vuepress && yarn install --immutable --immutable-cache --check-cache
      - name: ESLint
        run: cd vuepress && yarn eslint --ext .js,.vue . --fix